builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X github.com/gplassard/gh-github-repository-audit/cmd.Version={{.Version}}
      - -X github.com/gplassard/gh-github-repository-audit/cmd.Commit={{.Commit}}
      - -X github.com/gplassard/gh-github-repository-audit/cmd.Date={{.CommitDate}}
      - -X github.com/gplassard/gh-github-repository-audit/cmd.BuiltBy=goreleaser

archives:
  - format: binary
    name_template: "{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"